export const SET_LOGIN = 'SET_LOGIN'
export const GET_LOGIN = 'GET_LOGIN'
export const GET_DRIVERS = 'GET_DRIVERS'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'
export const GET_DELIVERIES = 'GET_DELIVERIES'
export const SET_STEP = 'SET_STEP'

export const GET_RECIPIENT_TITLE = 'GET_RECIPIENT_TITLE'
export const SET_RECIPIENT_TITLE = 'SET_RECIPIENT_TITLE'

export const DELIVERY_URL = 'https://utkeyrslukerfiapi.azurewebsites.net/api/deliveries'
export const LOGIN_URL = 'https://utkeyrslukerfiapi.azurewebsites.net/api/account/login'
export const LOGOUT_URL = 'https://utkeyrslukerfiapi.azurewebsites.net/api/account/logout'
export const DRIVER_LOGIN_URL = 'https://utkeyrslukerfiapi.azurewebsites.net/api/account/driverlogin'
export const DRIVERS_URL = 'https://utkeyrslukerfiapi.azurewebsites.net/api/users/drivers'

export const BLUE = '#4A79BA'
export const LIGHTER_BLUE = '#81ABE4'
export const LIGHT_BLUE = '#66C5FF'
export const GRAY_98 = '#FAFAFA'
export const MAINLY_BLUE = '#F0FBFC'
