export const SET_LOGIN = 'SET_LOGIN'
export const GET_LOGIN = 'GET_LOGIN'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'

export const SET_USER = 'SET_USER'
export const GET_USER = 'GET_USER'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const GET_VIEWING_USER = 'GET_VIEWING_USER'
export const SET_VIEWING_USER = 'SET_VIEWING_USER'
export const UPDATE_VIEWING_USER = 'UPDATE_VIEWING_USER'
export const GET_LOGGED_IN_USER = 'GET_LOGGED_IN_USER'
export const UPDATE_LOGGED_IN_USER = 'UPDATE_LOGGED_IN_USER'
export const GET_USERS = 'GET_USERS'

export const GET_DELIVERIES = 'GET_DELIVERIES'
export const GET_DELIVERY = 'GET_DELIVERY'
export const UPDATE_DELIVERY = 'UPDATE_DELIVERY'
export const SET_DELIVERY = 'SET_DELIVERY'

export const GET_PACKAGES = 'GET_PACKAGES'
export const GET_VIEWING_PACKAGE = 'GET_VIEWING_PACKAGE'
export const SET_VIEWING_PACKAGE = 'SET_VIEWING_PACKAGE'

// URLS
export const USER_URL = 'https://localhost:5001/api/users'
export const DELIVERY_URL = 'https://localhost:5001/api/deliveries'
export const LOGIN_URL = 'https://localhost:5001/api/account/login'
export const LOGOUT_URL = 'https://localhost:5001/api/account/logout'
