export const GET_USERS = 'GET_USERS'
export const CREATE_USER = 'CREATE_USER'
export const GET_DELIVERIES = 'GET_DELIVERIES'
export const GET_DELIVERY = 'GET_DELIVERY'
export const GET_PACKAGES = 'GET_PACKAGES'
export const UPDATE_DELIVERY = 'UPDATE_DELIVERY'
export const GET_USER = 'GET_USER'
export const SET_EMAIL = 'SET_EMAIL'
export const GET_EMAIL = 'GET_EMAIL'
export const UPDATE_USER = 'UPDATE_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const GET_TOKEN = 'GET_TOKEN'
// URLS
export const USER_URL = 'https://localhost:5001/api/users'
export const DELIVERY_URL = 'https://localhost:5001/api/deliveries'
export const LOGIN_URL = 'https://localhost:5001/api/account/login'
