name: CD for Utkeyrslukerfi
on: [push] 
env: 
  AZURE_WEBAPP_PACKAGE_PATH: './Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/'
  DOTNET_VERSION: '5.0.103'
jobs: 
  build: 
    runs-on: windows-latest 
    steps: 
      - name: Sample Azure action
        with: # Set Azure credentials secret as an input
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
        env: # Or as an environment variable
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/setup-dotnet@v1 
      - name: switch
      # Checkout the repo 
      - uses: actions/checkout@ermir 
      # Run dotnet build and publish 
      - name: dotnet build and publish 
        working-directory: ./Backend/Utkeyrslukerfi.API/Utkeyrslukerfi.API/
        run: | 
          dotnet restore 
          dotnet build --configuration Release 
          dotnet publish -c Release -o '$/myApp'  
           
      # Deploy to Azure Web apps 
      - name: 'Run Azure webapp deploy action using azure credentials' 
        uses: azure/webapps-deploy@v2 
        with:  
          app-name: Utkeyrslukerfi
          package: '$/myApp' 
       
      - name: logout 
        run: | 
          az logout

