---
# This is a basic workflow to help you get started with Actions
name: CI Linter

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request
  # request events but only for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more 
# jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Linter
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that 
    # will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
