# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: CI React Web

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      working-directory: ./Web/utkeyrslukerfi-web/
      run: npm install

    # - name: Run the tests
    #   working-directory: ./Web/utkeyrslukerfi-web/
    #   run: npm test
  
    - name: Build
      working-directory: ./Web/utkeyrslukerfi-web/
      run: npm run build

